# Include civicrm specific configuration
- include_vars: "{{ item }}"
  with_items:
    - civicrm.yml
    - version.yml
  tags:
    - configuration
    - update

- name: General | Install Application packages
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl

- name: Civicrm | Ensure MySQL is running
  command: service mysql start
  ignore_errors: yes
  tags:
    - configuration

- name: Civicrm | Create Civicrm database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ civicrm_db_name }}"
    state: present

- name: Civicrm | Create Civicrm database user
  mysql_user:
    name: "{{ civicrm_db_user }}"
    password: "{{ civicrm_db_password }}"
    priv: "{{ civicrm_db_name }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Civicrm | Download application from Github
  sudo: false
  git:
    repo: "https://github.com/{{ application_repository }}/civiCRM.git"
    dest: "{{ civicrm_root_path }}"
    version: "{{ application_version }}"
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
    update: yes
    force: yes
  tags:
    - update

- name: Civicrm | Current commit hash
  shell: 'git log -n 1 --pretty=format:"%H" > {{ civicrm_root_path }}/.git-version'
  args:
    chdir: "{{ civicrm_root_path }}"
  tags:
    - update

- name: Git | Ignore files permissions changes
  command: "git config core.filemode false chdir={{ civicrm_root_path }}"
  tags:
    - update

- name: Ansible | Update scripts
  copy:
    src: "{{ civicrm_root_path }}/deploy/ansible"
    dest: /etc/
  tags:
    - update

- name: Civicrm | Configure Apache virtual host
  template: 
    src: etc-apache24-confd-civicrm-conf
    dest: /etc/apache2/sites-available/civicrm.conf
    owner: root
    mode: 755
  tags:
    - configuration

- name: Civicrm | Enable Apache virtual host 
  file: src=/etc/apache2/sites-available/civicrm.conf dest=/etc/apache2/sites-enabled/civicrm.conf state=link
  tags:
    - configuration

- name: Apache | Restart the Apache service
  service: 
    name: apache2 
    state: restarted

- name: Civicrm | Configuration file drupal-settings.php
  template: 
    src: drupal-settings.php
    dest: "{{ civicrm_root_path }}/sites/default/settings.php"
    owner: www-data
    mode: 755
  tags:
    - configuration

- name: Civicrm | Install drupal core
  shell: "drush -y site-install standard --account-name=\"alpha7\" --account-pass=\"alpha72015!@\" --db-url=\"mysql://{{civicrm_db_user}}:{{civicrm_db_password}}@localhost/{{civicrm_db_name}}\""    
  args:
    chdir: "{{ civicrm_root_path }}"

- name: Civicrm | Install Drush Command for civiCRM
  shell: "cp sites/all/modules/civicrm/drupal/drush/civicrm.drush.inc $HOME/.drush/civicrm.drush.inc"
  args:
    chdir: "{{ civicrm_root_path }}"

- name: Civicrm | Enable CiviCRM Module
  shell: "drush civicrm-install"
  args:
    chdir: "{{ civicrm_root_path }}"       
    

- name: Civicrm | Configuration file alpha7.json
  template: 
    src: civicrm-alpha7.json
    dest: "{{ civicrm_root_path }}/alpha7.json"
    owner: www-data
    group: www-data
    mode: 777
  tags:
    - configuration


- name: Civicrm | Set file permissions
  file:
    path: "{{ civicrm_root_path }}"
    mode: 0755
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  tags:
    - configuration

- name: DCivicrm | Set log files permissions
  file:
    path: /var/log/apache2
    mode: 0755
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  tags:
    - configuration
